name: mirm_core
main: mirm_core\mirm_core
version: 1u1
api: [2.0.0]
load: POSTWORLD
author: haniokasai
description: MiRm Core Plugin
website: haniokasai.com

commands:
 stat:
  description: "チームの人数確認"
 mi:
  description: "自分の状態がわかります"
 pvp:
  description: "pvpに参加"
 rank:
  description: "称号"
 c:
  description: "チームチャット"
 gm:
  description: "閲覧モード/サバイバル（アイテムが消えるので注意)"
 pban:
  description: "閲覧モード/サバイバル（アイテムが消えるので注意)"
permissions:
 stat:
  default: true
 mi:
  default: true
 pvp:
  default: true
 rank:
  default: true
 c:
  default: true
 gm:
  default: true
 pban:
  default: true